# Generated by Django 5.1.1 on 2026-02-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Индентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчеркивание.', unique=True, verbose_name='Индентификатор'),
        ),
    ]
