# Generated by Django 5.1.1 on 2026-02-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='title',
            field=models.CharField(default=0, max_length=256, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
