# Generated by Django 5.1.1 on 2026-02-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_location_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='title',
        ),
    ]
